# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Fix ESLint

on: [workflow_dispatch] # Can only be triggered manually

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: CI
      run: npm ci --no-optional

    - name: Build
      run: npm run build --if-present

    - name: Fix EsLint
      run: npm run eslint:fix
      
    - name: Commit
      run: |
        git config --global user.email "hypixel-api-reborn@github.com"
        git config --global user.name "Auto EsLint"
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        git pull github ${GITHUB_REF} --ff-only
        git add .
        git commit -m "Automatic Lint"
        git push github HEAD:${GITHUB_REF}
